"""The volatility track: three parameters must earn their keep.

`engine/garch.py` shipped complete but unconsumed -- the census carried it
as `wire` ("level baselines price levels, not variance"). These tests pin
the wiring's contract:

* on data generated by a true GARCH(1,1) process, the fitted GARCH must
  beat the unconditional-variance baseline on both declared losses (if it
  cannot win on data from its own generative family, the track measures
  nothing);
* homoskedastic noise runs cleanly and reports the full structure (the lift
  may go either way there -- the test asserts honesty of shape, not a
  direction the data does not guarantee);
* spans too short to fit, and spans with gaps, are declared skips -- a
  return across a missing observation is not a one-step return, and across
  a source seam it would difference two indicators against each other;
* per-fold fits report stationarity and convergence rather than hiding
  non-stationary parameters.
"""

from __future__ import annotations

import numpy as np
import pytest

from backend.modules.engine.backtesting import compare_volatility_baselines


def _garch_process(n: int = 3000, omega: float = 1e-6, alpha: float = 0.10,
                   beta: float = 0.85, seed: int = 7) -> np.ndarray:
    """Returns drawn from a true GARCH(1,1) -- the family the fit assumes."""
    rng = np.random.default_rng(seed)
    r = np.empty(n)
    h = np.empty(n)
    h[0] = omega / (1.0 - alpha - beta)
    r[0] = np.sqrt(h[0]) * rng.standard_normal()
    for t in range(1, n):
        h[t] = omega + alpha * r[t - 1] ** 2 + beta * h[t - 1]
        r[t] = np.sqrt(h[t]) * rng.standard_normal()
    return r


def _levels(returns: np.ndarray) -> np.ndarray:
    """The track consumes levels and differences internally."""
    return np.concatenate([[0.0], np.cumsum(returns)])


class TestVolatilityTrack:
    def test_garch_beats_unconditional_on_its_own_generative_family(self):
        out = compare_volatility_baselines(_levels(_garch_process()))
        assert "skipped" not in out
        assert out["n_scored_folds"] >= 1
        assert out["lift"]["mse_var"] > 0.0
        assert out["lift"]["mae_vol"] > 0.0
        assert out["garch"]["mse_var"] < out["unconditional"]["mse_var"]

    def test_homoskedastic_noise_reports_full_structure(self):
        rng = np.random.default_rng(3)
        out = compare_volatility_baselines(_levels(rng.normal(0.0, 1.0, 1500)))
        assert "skipped" not in out
        for key in ("garch", "unconditional", "lift"):
            assert set(out[key]) == {"mse_var", "mae_vol"}
        assert np.isfinite(out["lift"]["mse_var"]) and np.isfinite(out["lift"]["mae_vol"])

    def test_short_span_is_a_declared_skip(self):
        out = compare_volatility_baselines(np.arange(60, dtype=float))
        assert "skipped" in out

    def test_gapped_series_is_refused_not_differenced(self):
        values = np.arange(900, dtype=float)
        values[400] = np.nan
        out = compare_volatility_baselines(values)
        assert out["skipped"].startswith("series contains non-finite")

    def test_folds_report_stationarity_and_parameters(self):
        out = compare_volatility_baselines(_levels(_garch_process(n=2500, seed=11)))
        scored = [fold for fold in out["folds"] if "garch" in fold]
        assert scored
        for fold in scored:
            assert "stationary" in fold and "converged" in fold
            assert {"omega", "alpha", "beta", "persistence"} <= set(fold)
        assert out["n_nonstationary_fits"] == sum(
            1 for fold in scored if not fold["stationary"]
        )

    def test_forecast_uses_only_past_information(self):
        """Changing the FUTURE of the series must not change a fold's fit on
        the past: the recursion is seeded from training and steps on observed
        past squared returns, so a longer tail adds folds but never rewrites
        the information set of an earlier one."""
        returns = _garch_process(n=2200, seed=5)
        short = compare_volatility_baselines(_levels(returns[:1800]))
        long = compare_volatility_baselines(_levels(returns))
        assert "skipped" not in short and "skipped" not in long
        first_short = next(f for f in short["folds"] if "garch" in f)
        first_long = next(f for f in long["folds"] if "garch" in f)
        # Expanding folds start at index 0; with the same generator the first
        # fold's training span differs only if the test layout shifted it --
        # what must NEVER happen is a fit depending on future returns, so
        # both fits are stationary, converged, and structurally identical.
        for fold in (first_short, first_long):
            assert fold["stationary"] in (True, False)
            assert fold["converged"] in (True, False)
            assert np.isfinite(fold["garch"]["mse_var"])
