"""Risk analysis constants and thresholds."""

# Risk level thresholds (0-1 scale)
RISK_THRESHOLD_LOW = 0.3
RISK_THRESHOLD_MODERATE = 0.6
RISK_THRESHOLD_HIGH = 0.85

# Risk level thresholds (0-100 scale)
RISK_THRESHOLD_LOW_PERCENT = 30
RISK_THRESHOLD_MODERATE_PERCENT = 60
RISK_THRESHOLD_HIGH_PERCENT = 80

# Systemic risk thresholds
SYSTEMIC_RISK_THRESHOLD_MODERATE = 60
SYSTEMIC_RISK_THRESHOLD_HIGH = 80

# High risk thresholds for network analysis
HIGH_RISK_THRESHOLD = 0.7
CRITICAL_RISK_THRESHOLD = 0.9

# Contagion analysis
SIGNIFICANT_CONNECTIONS_THRESHOLD = 10

# Feature importance thresholds
SIGNIFICANT_CONTRIBUTION_THRESHOLD = 0.1

# Confidence interval thresholds
CONFIDENCE_WIDTH_NARROW = 0.1
CONFIDENCE_WIDTH_MODERATE = 0.3

# Data quality thresholds
MISSING_DATA_THRESHOLD = 0.3
DATA_QUALITY_THRESHOLD_GOOD = 60.0

# Model performance thresholds
R2_EXCELLENT_THRESHOLD = 0.95
R2_GOOD_THRESHOLD = 0.8
R2_PRODUCTION_THRESHOLD = 0.9
R2_TESTING_THRESHOLD = 0.7

# Memory thresholds (GB)
MEMORY_MINIMUM_GB = 16
MEMORY_RECOMMENDED_GB = 32
GPU_MEMORY_MINIMUM_GB = 8
GPU_MEMORY_RECOMMENDED_GB = 24

# Temporal analysis window sizes
RECENT_DATA_WINDOW = 10
TEMPORAL_WINDOW_SHORT = 7
TEMPORAL_WINDOW_MEDIUM = 14

# Volatility thresholds
MARKET_VOLATILITY_HIGH_THRESHOLD = 15
VOLATILITY_NORMALIZATION_FACTOR = 0.1
TREND_NORMALIZATION_FACTOR = 0.01

# Operational risk bounds
OPERATIONAL_RISK_MINIMUM = 0.1
OPERATIONAL_RISK_MAXIMUM = 0.6
OPERATIONAL_RISK_DEFAULT = 0.3

# Risk score weights
WEIGHT_MARKET_LIQUIDITY = 0.35
WEIGHT_FUNDING_LIQUIDITY = 0.35
WEIGHT_SYSTEMIC_RISK = 0.25
WEIGHT_OPERATIONAL_RISK = 0.05

# Network contagion weights
WEIGHT_INDIVIDUAL_RISK = 0.4
WEIGHT_SYSTEMIC_CONCENTRATION = 0.3
WEIGHT_NETWORK_INTERCONNECTEDNESS = 0.3

# Correlation analysis
CORRELATION_THRESHOLD = 0.5
CORRELATION_P_VALUE_THRESHOLD = 0.05

# Data quality weights
WEIGHT_DATA_COMPLETENESS = 0.6
WEIGHT_DATA_CONSISTENCY = 0.4

# Data analysis weights
WEIGHT_VALIDATION_RESULTS = 0.4
WEIGHT_DATA_COMPLETENESS_ANALYSIS = 0.3
WEIGHT_CLEANING_SUCCESS = 0.3

# Orchestrator thresholds
DATA_QUALITY_THRESHOLD = 70.0
DATA_COMPLETENESS_MINIMUM = 80.0

# Sequence lengths
DEFAULT_SEQUENCE_LENGTH = 30

# Model defaults
DEFAULT_HIDDEN_DIM = 128
DEFAULT_NUM_HEADS = 8
DEFAULT_NUM_LAYERS = 3

# Vulnerability normalization
VULNERABILITY_NORMALIZATION_FACTOR = 1e9
