"""API routes."""

from . import (
    data_sources,
    assets,
    jobs,
    jobs_ws,
    config,
    system,
    errors,
    catalogue,
    pipeline,
    results,
    explainability,
    data_explorer_v2,
    reports_v2,
    models_v1,
    predictions_v2,
    countries,
    notifications,
    data_quality,
    analytics,
    alert_rules,
    reports,
)

__all__ = [
    "data_sources",
    "assets",
    "jobs",
    "jobs_ws",
    "config",
    "system",
    "errors",
    "catalogue",
    "pipeline",
    "results",
    "explainability",
    "data_explorer_v2",
    "reports_v2",
    "models_v1",
    "predictions_v2",
    "countries",
    "notifications",
    "data_quality",
    "analytics",
    "alert_rules",
    "reports",
]
