"""Regenerate ``docs/api-endpoints.md`` from the live FastAPI application.

Why this exists
---------------
``docs/api_v2.md`` was hand-maintained and drifted badly: by the time it was
removed, seven of the fourteen endpoints it documented did not exist, and the UI
it described had been replaced. A hand-written inventory of routes fails
silently — it keeps reading plausibly long after it stops being true.

This script removes the opportunity. It reads the OpenAPI schema that FastAPI
itself serves at ``/openapi.json`` (the same document behind ``/docs``), so the
inventory cannot disagree with the running application.

What this is NOT
----------------
It does not document request/response *bodies*. Those are declared by the
Pydantic schemas and are authoritative at runtime; reproducing them by hand here
would recreate the exact drift this script exists to prevent. Use
``/docs`` and ``/openapi.json`` for field-level detail. This file answers only
"which endpoints exist, and under which tag".

It also does not import the app's lifespan: no database connection is opened and
no model is loaded. Import is sufficient, because routers are registered at
module import time.

Usage
-----
    PYTHONPATH=. python scripts/generate_api_docs.py [--check]

``--check`` exits non-zero if the file on disk differs from the generated text,
which is what a CI job would call to detect a stale inventory.
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "docs" / "api-endpoints.md"

# Display order. Tags missing from this list are appended alphabetically, so
# adding a router without touching this file still produces a complete document.
TAG_ORDER = (
    "Pipeline (DATA-ENGINE-RESULTS)",
    "Jobs",
    "Jobs WebSocket",
    "Data Sources",
    "Data Catalogue",
    "Assets",
    "Results & Reports",
    "AI Explainability (EU Compliant)",
    "Model Catalogue",
    "Country Profiles",
    "Data Quality",
    "Notifications",
    "Error Logging",
    "Configuration",
    "System",
    "Data Explorer v2",
    "Reports v2",
    "Predictions v2",
    "Advanced Analytics",
    "Alert Rules",
    "Observations (Point-in-Time)",
)

METHOD_ORDER = ("get", "post", "put", "patch", "delete")

HEADER = """\
<!-- Generated by scripts/generate_api_docs.py from the FastAPI OpenAPI schema. -->
<!-- Do not edit by hand: run `PYTHONPATH=. python scripts/generate_api_docs.py`. -->

# API endpoint inventory

Every route the application actually serves, read from the OpenAPI schema that
FastAPI generates at import time. This file is **generated** — see
[`scripts/generate_api_docs.py`](../scripts/generate_api_docs.py). Field-level
request and response bodies are not reproduced here; read them from the live
schema at `/openapi.json` or the Swagger UI at `/docs`.

"""


def _summary(operation: dict) -> str:
    """First sentence of the handler docstring, else FastAPI's auto-summary.

    The docstring is preferred because FastAPI derives ``summary`` from the
    function name, so a handler called ``get_data_quality_stats`` yields the
    bare "Get Data Quality Stats" while its docstring says what the endpoint
    actually returns. Only the first sentence is kept — the rest is usually
    addressed to non-technical users and belongs in the Swagger UI.
    """
    text = operation.get("description") or operation.get("summary") or ""
    first = " ".join(text.split()).split(". ")[0].strip()
    if not first:
        return "—"
    return first if first.endswith(".") else first + "."


def _response_model(operation: dict) -> str:
    """The declared success response model, or a dash when there is none.

    FastAPI emits a schema reference such as
    ``#/components/schemas/JobResponse`` for a typed handler, and either no
    ``content`` or a bare ``{}`` for a handler that returns an untyped dict.
    Both of those are reported honestly rather than guessed at.
    """
    for status in ("200", "201", "202"):
        response = operation.get("responses", {}).get(status)
        if not response:
            continue
        for media in response.get("content", {}).values():
            ref = media.get("schema", {}).get("$ref")
            if ref:
                return f"`{ref.rsplit('/', 1)[-1]}`"
        return "untyped"
    return "—"


def collect(spec: dict) -> dict[str, list[tuple[str, str, str, str]]]:
    """Group ``(method, path, response model, summary)`` tuples by tag."""
    grouped: dict[str, list[tuple[str, str, str, str]]] = {}
    for path, operations in spec.get("paths", {}).items():
        for method, operation in operations.items():
            if method not in METHOD_ORDER:
                continue  # skip `parameters`, `servers`, etc.
            tags = operation.get("tags") or ["(untagged)"]
            for tag in tags:
                grouped.setdefault(tag, []).append(
                    (method, path, _response_model(operation), _summary(operation))
                )
    for entries in grouped.values():
        entries.sort(key=lambda row: (row[1], METHOD_ORDER.index(row[0])))
    return grouped


def render(spec: dict) -> str:
    grouped = collect(spec)
    ordered_tags = [t for t in TAG_ORDER if t in grouped]
    # Untagged routes (/, /health) sort last rather than under a bracket, which
    # would otherwise place them above every named tag.
    ordered_tags += sorted(
        (t for t in grouped if t not in TAG_ORDER), key=lambda t: (t.startswith("("), t)
    )

    out = [HEADER]
    info = spec.get("info", {})
    out.append(
        f"Application: **{info.get('title', 'BEACON API')}** "
        f"v{info.get('version', '?')}\n"
    )
    total = sum(len(grouped[t]) for t in ordered_tags)
    out.append(f"**{total} operations across {len(grouped)} tags.**\n")

    for tag in ordered_tags:
        entries = grouped[tag]
        out.append(f"\n## {tag}\n")
        out.append("| Method | Path | Success model | Purpose |")
        out.append("|---|---|---|---|")
        for method, path, model, summary in entries:
            out.append(f"| `{method.upper()}` | `{path}` | {model} | {summary} |")
        out.append("")

    out.append(
        "\n---\n\nHand-written protocol notes — the error envelope, the job "
        "WebSocket handshake, and the data-quality score — are in "
        "[`api.md`](api.md).\n"
    )
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the file on disk is not what would be generated",
    )
    args = parser.parse_args()

    sys.path.insert(0, str(REPO_ROOT))
    from backend.api.main import app  # imported lazily so --help needs no deps

    generated = render(app.openapi())

    if args.check:
        current = ""
        if OUTPUT_PATH.exists():
            current = OUTPUT_PATH.read_text(encoding="utf-8")
        if current != generated:
            diff = difflib.unified_diff(
                current.splitlines(),
                generated.splitlines(),
                fromfile=str(OUTPUT_PATH),
                tofile="generated",
                lineterm="",
            )
            sys.stderr.write("\n".join(diff) + "\n")
            sys.stderr.write(
                "\ndocs/api-endpoints.md is stale. Run "
                "`PYTHONPATH=. python scripts/generate_api_docs.py`.\n"
            )
            return 1
        print("docs/api-endpoints.md is current.")
        return 0

    OUTPUT_PATH.write_text(generated, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
